
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmgeceixlemojtlnqxph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtZ2VjZWl4bGVtb2p0bG5xeHBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMDI0OTgsImV4cCI6MjA2MDc3ODQ5OH0.81C9Lqwn7nC54zdRM_Pcl2EkFJsWClE7RzFj3COQZVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
